services:
  demo_dbPostgressquiz:
    container_name: demo_dbPostgressquiz
    image: postgres:16.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senha1234
      POSTGRES_USER: usuario
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - juntatudo

  demo_minio:
    container_name: demo_minio
    image: quay.io/minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_VOLUMES: "/data"
      MINIO_NOTIFY_POSTGRES_ENABLE: "on"
      MINIO_NOTIFY_POSTGRES_CONNECTION_STRING: "host=demo_dbPostgressquiz user=usuario password=senha1234 dbname=postgres sslmode=disable"
      MINIO_NOTIFY_POSTGRES_TABLE: "minio"
      MINIO_NOTIFY_POSTGRES_FORMAT: "namespace"
    volumes:
      - ./minio-data:/data
    command: server --console-address "0.0.0.0:9090" /data --address 0.0.0.0:9000
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      test: ["CMD", "curl", "-f"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - demo_dbPostgressquiz
    networks:
      - juntatudo
  demo_keycloak:
    container_name: demo_keycloak
    image: quay.io/keycloak/keycloak
    restart: always
    hostname: keycloak.quiz.local
    domainname: quiz.local
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: senha1234
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://demo_dbPostgressquiz:5432/postgres
      KC_DB_USERNAME: usuario
      KC_DB_PASSWORD: senha1234
      KC_COOKIE_SECURE: false
      KEYCLOAK_COOKIE_SECURE: false
      #KC_HOSTNAME: localhost
      #KC_LOG_LEVEL: DEBUG
    depends_on:
      - demo_dbPostgressquiz
    command: ["start-dev","--http-host=0.0.0.0"]
    volumes:
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
      - ./keycloak-themes:/opt/jboss/keycloak/themes
      - ./keycloak-realm:/opt/jboss/keycloak/standalone/configuration/keycloak-realm.json
    networks:
      - juntatudo
    
networks:
  juntatudo:
    driver: bridge
    
  # mailserver:
  #   image: ghcr.io/docker-mailserver/docker-mailserver:latest
  #   container_name: mailserver
  #   hostname: mail.quiz.local
  #   ports:
  #   - "25:25"
  #   - "465:465"
  #   - "587:587"
  #   - "993:993"
  #   volumes:
  #     - ./docker-data/dms/mail-data/:/var/mail/
  #     - ./docker-data/dms/mail-state/:/var/mail-state/
  #     - ./docker-data/dms/mail-logs/:/var/log/mail/
  #     - ./docker-data/dms/config/:/tmp/docker-mailserver/
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - ENABLE_RSPAMD=1
  #     - ENABLE_CLAMAV=1
  #     - ENABLE_FAIL2BAN=1
  #   cap_add:
  #     - NET_ADMIN # For Fail2Ban to work
  #   restart: always
  # não funcionou :(
